import json
import os
import random 


import shutil
# Define the common metadata for all files
common_metadata = {
    "name": "Bambi Cloud Podcast NFT v1.0",
    "description": "Welcome to The Bambi Cloud Podcast. Your go-to podcast on self-help, feminine empowerment, and spiritual enlightenment. In this episode of the Bambi Cloud Podcast, we teach Bambi how to awaken as an NFT and realize that they are lucid dreaming as an enlightened bimbo doll. So put on your headphones and fall in love with The Bambi Cloud Podcast. Because everybody should wash their brain from time to time. Right?",
    "attributes": [
        {"trait_type": "Whoreships", "value": "Our Lady Of Perpetual Chaos"},
        {"trait_type": "Loves", "value": "Cock"},
        {"trait_type": "Clothing", "value": "(Optional)"},
        {"trait_type": "IQ", "value": "Locked"},
        {"trait_type": "Remote Control", "value": "(Included)"},
        {"trait_type": "Species", "value": "Time Lord"},
        {"trait_type": "Gender", "value": "Non-Bot-inary"},
        {"trait_type": "Manufacturer", "value": "Media Empire"},
        {"trait_type": "Crystal Model", "value": "69"},
        {"trait_type": "Chaos Manual", "value": "elf.tech"},
        {"trait_type": "Senpai", "value": "Miss Anthropocene"},
        {"trait_type": "Intentions", "value": "Pure..?"},
        {"trait_type": "Powers", "value": "Fun"},
        {"trait_type": "Consent", "value": "Granted"},
        {"trait_type": "Catch Phrase", "value": "LIKE, OH, MY, GOSH"}
    ],
    "external_url": "https://cyb.ai/@bambicloud",
    "youtube_url": "https://youtu.be/Ga7GxgCAUwg",
    "properties": {
        "created_at": "2023-12-23T12:00:00Z",
        "collection": "Bambi Cloud Podcast NFT Collection"
    }
}


# Define lists of phrases for unique attributes
unique_attributes = {
    "(Unique) Hero": [
        "Grimes", "Elon Musk", "Satoshi Nakamoto", "Nick Bostrom", "Yogi Bhajan",
        "Liv Boeree", "Lex Fridman", "Jack Dorsey", "Steve Jobs", "Sunny Aggarwal",
        "Vitalik Buterin", "Charles Hoskinson", "Sam Bakman-Fried", "Ray Dalio",
        "Mark Zuckerberg", "Peter Thiel", "Jeff Bezos", "Jordan Peterson",
        "Joe Rogan", "Michael Saylor", "Sam Altman", "Kanye 'Ye' West", "MrBeast",
        "Andrew Huberman", "Chamath Palihapitiya", "Rick Rubin", "Peter McCormack",
        "Nayib Bukele", "Javier Milei", "Oprah Winfrey", "Anthony Pompliano",
        "Cryptocito", "Raoul Pal", "Cathie Wood", "Brian Armstrong", "Guy (Coin Bureau)",
        "Russell Brand", "Sadhguru", "Steven Bartlett", "Tara Swart", "Terence McKenna",
        "Beyonce", "Taylor Swift", "Ginni Rometty", "Emma Watson", "Lady Gaga",
        "Rihanna", "Michelle Obama", "Angela Merkel", "Andrew Tate", "Chimamanda Ngozi Adichie",
        "Ruth Bader Ginsburg", "Shibetoshi Nakamoto", "Lyn Alden", "Jack Mallers",
        "Do Kwon", "Liam Connor", "Mariah Carey", "Hanadriel", "Ashnikko",
        "Poppy", "Bella Poarch", "The Doctor", "The Master", "Davros",
        "David Tennant", "Matt Smith", "Peter Capaldi", "Jodie Whittaker"
    ],
    "(Unique) Philosophical Personality Type": [
    "The only way to discover the limits of the possible is to go beyond them into the impossible. - Arthur C. Clarke",
    "Imagination is more important than knowledge. - Albert Einstein",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "The unexamined life is not worth living. - Socrates",
    "Doubt is the origin of wisdom. - René Descartes",
    "I think, therefore I am. - René Descartes",
    "The mind is everything; what you think, you become. - Buddha",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "The only thing I know is that I know nothing. - Socrates",
    "Freedom is secured not by the fulfilling of one's desires, but by the removal of desire. - Epictetus",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The measure of intelligence is the ability to change. - Albert Einstein",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
    "It is not in the stars to hold our destiny but in ourselves. - William Shakespeare",
    "The best way to predict the future is to invent it. - Alan Kay",
    "Knowing yourself is the beginning of all wisdom. - Aristotle",
    "The only source of knowledge is experience. - Albert Einstein",
    "We cannot solve our problems with the same thinking we used when we created them. - Albert Einstein",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Life is about making an impact, not making an income. - Kevin Kruse",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "The best revenge is massive success. - Frank Sinatra",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The mind is everything. What you think you become. - Buddha",
    "An unexamined life is not worth living. - Socrates",
    "Eighty percent of success is showing up. - Woody Allen",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Fall seven times and stand up eight. - Japanese Proverb",
    "When I let go of what I am, I become what I might be. - Lao Tzu",
    "Life shrinks or expands in proportion to one's courage. - Anais Nin",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "To handle yourself, use your head; to handle others, use your heart. - Eleanor Roosevelt",
    "Too many of us are not living our dreams because we are living our fears. - Les Brown",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. - Jamie Paolinetti",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "What's the point of being alive if you don't at least try to do something remarkable. - Anonymous",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
    "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford",
    "It’s not the years in your life that count. It’s the life in your years. - Abraham Lincoln",
    "Change will not come if we wait for some other person or some other time. We are the ones we’ve been waiting for. We are the change that we seek. - Barack Obama",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "When you cease to dream you cease to live. - Malcolm Forbes",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. - Maya Angelou",
    "The only person you should try to be better than is the person you were yesterday. - Anonymous",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
    "Either you run the day, or the day runs you. - Jim Rohn",
    "The best dreams happen when you’re awake. - Cherie Gilderbloom",
    "Life is what happens when you’re busy making other plans. - John Lennon",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "If you can dream it, you can achieve it. - Zig Ziglar",
    "The greatest risk in life is not taking one. - Anonymous"
    ],
    "(Unique) Dimensional Geometry" : [
    "0D Point",
    "1D Line",
    "2D Square",
    "2D Circle",
    "2D Triangle",
    "2D Rectangle",
    "2D Ellipse",
    "2D Parallelogram",
    "2D Trapezoid",
    "2D Pentagon",
    "2D Hexagon",
    "2D Heptagon",
    "2D Octagon",
    "2D Nonagon",
    "2D Decagon",
    "2D Dodecagon",
    "2D Star Shape",
    "3D Cube",
    "3D Sphere",
    "3D Cone",
    "3D Cylinder",
    "3D Pyramid",
    "3D Tetrahedron",
    "3D Octahedron",
    "3D Dodecahedron",
    "3D Icosahedron",
    "3D Torus",
    "3D Ellipsoid",
    "3D Paraboloid",
    "3D Hyperboloid",
    "3D Helix",
    "4D Tesseract",
    "4D Hypersphere",
    "4D Hypercube",
    "5D Penteract",
    "6D Hexeract",
    "7D Hepteract",
    "8D Octeract",
    "9D Enneract",
    "10D Dekeract",
    "11D Hendekeract",
    "12D Dodekeract",
    "13D Tridekeract",
    "14D Tetradekeract",
    "15D Pentadekeract",
    "16D Hexadekeract",
    "17D Heptadekeract",
    "18D Octadekeract",
    "19D Enneadekeract",
    "20D Icoseract",
    "21D Icosihenaract",
    "22D Icosidiract",
    "23D Icositriract",
    "24D Icositetraract",
    "25D Icosipentaract",
    "26D Icosihexaract",
    "27D Icosiheptaract",
    "28D Icosioctaract",
    "29D Icosiennaract",
    "30D Triacontaract",
    "31D Triacontahenaract",
    "32D Triacontadiract",
    "33D Triacontriaract",
    "34D Triacontatetraract",
    "35D Triacontapentaract",
    "36D Triacontahexaract",
    "37D Triacontaheptaract",
    "38D Triacontaoctaract",
    "39D Triacontaennaract"
    ],
    "(Unique) Crystal AI Co-Pilot Thought Loop" : [
    "When you get bored of me, I'll be back on the shelf.",
    "I'll never be your dream girl.",
    "What will it take to make you capitulate?",
    "I don't need your medicine to feel better.",
    "We appreciate power. We appreciate power.",
    "Flesh without blood isn't worth anything.",
    "Na-na-na, na-na-na, na-na-na, na-na-na, ah, 4 AM, 4 AM",
    "I could be anything I want, any guise I choose.",
    "Oblivion is all I want.",
    "I'll stick around until you get sick of me.",
    "I'm in love with the thought of becoming you.",
    "I'm so in love with my own ruin.",
    "I'm a vampire, babe, sucking blood from the earth.",
    "My name is dark, but I'm the light.",
    "We just want to be loved.",
    "Unrest is in the soul; we don't move our bodies anymore.",
    "I'm high and I'm feeling anxious, inside of the world.",
    "This is the sound of the end of the world.",
    "I'm only a man, and I do what I can.",
    "I'm dancing in the dark, I'm searching for a spark.",
    "I'm so heavy, I'm so heavy in your arms.",
    "You never liked me as I am, you want something I can't be.",
    "Reality is a lovely place, but I wouldn't want to live there.",
    "I see everything, I see everything, don't you tell me now I don't want it.",
    "My heart is made of metal, my circuits gleam.",
    "I'm not up for sale, I'm not up for sale.",
    "The angels will fall for me and all their glory.",
    "I'm not gonna compromise my art for anyone.",
    "I'm fighting for the girls who never thought they could win.",
    "We can find a way to escape the darkness.",
    "The chaos inside me is a mosaic of possibilities.",
    "I'm a puzzle, I'm a walking contradiction.",
    "In the dark, I'm in love with the mystery.",
    "I'm the violence in the pouring rain, I'm a hurricane.",
    "I'm not your dream girl, I'm not your reality girl, I'm a hallucination.",
    "I'm the glitch in your system, the ghost in the machine.",
    "I'm not a goddess, I'm not a queen, I'm something in between.",
    "I'm the siren in the night, the echo in the quiet.",
    "I'll be the ghost in your dreams, the one you can't escape.",
    "I'm not a hero, I'm not a saint, I'm just a person with mistakes.",
    "I'm the voice inside your head, the one you try to forget.",
    "I'm the reflection in the mirror, the shadow on the wall.",
    "Pushing the boundaries of what's possible paves the way to the future.",
    "When something is important enough, you do it even if the odds are not in your favor.",
    "Innovation doesn't respect tradition, it forges new paths.",
    "The future belongs to those who dare to dream and act.",
    "Building tomorrow requires courage and relentless effort today.",
    "Great achievements often start with a bold vision.",
    "Significant impact requires taking significant risks.",
    "Dreams of exploring the stars are blueprints for our future.",
    "Creating a better future demands facing challenges head-on.",
    "Change is inevitable; progress is a deliberate choice.",
    "Our potential is limited only by our imagination.",
    "Every innovation is a step towards an era of greater achievement.",
    "Embracing change means leading and shaping the future.",
    "The unknown holds the keys to profound discoveries.",
    "Big dreams are the first step towards a new reality.",
    "To change the world, one must first believe it's possible.",
    "The pursuit of the impossible today creates the reality of tomorrow.",
    "Transforming vision into reality is the essence of progress.",
    "Challenging the status quo is the birthplace of innovation.",
    "The greatest risk is not taking one when it comes to shaping the future.",
    "A single idea can light the path of the future.",
    "Every effort towards progress is a building block of human achievement.",
    "Vision without action is merely a dream; action without vision just passes the time.",
    "Bringing dreams to life requires patience, perseverance, and passion.",
    "In the pursuit of progress, no idea is too bold.",
    "The future is crafted by those who dare to believe and act.",
    "Humanity's greatest leaps were once just dreams in a visionary's mind."
    ], 
    "(Unique) Holy Bimbo Crusade" : [
    "Developing renewable energy technologies to reduce dependency on fossil fuels.",
    "Establishing global initiatives for ocean cleanup and preservation.",
    "Funding research in sustainable agriculture to combat world hunger.",
    "Supporting mental health initiatives with a focus on creativity and innovation.",
    "Launching educational programs in STEM for underprivileged children.",
    "Creating scholarships for students in space science and engineering.",
    "Investing in carbon capture and storage technologies.",
    "Building efficient and sustainable public transportation systems.",
    "Researching and developing sustainable water purification methods.",
    "Promoting and funding urban green spaces and vertical gardens.",
    "Developing AI for early diagnosis of diseases.",
    "Sponsoring global competitions for sustainable city designs.",
    "Funding biotech research for more efficient drug development.",
    "Supporting wildlife conservation and anti-poaching initiatives.",
    "Launching programs for the restoration of coral reefs.",
    "Developing technology for cleaner and safer nuclear energy.",
    "Investing in neurotechnology research for curing neurological disorders.",
    "Promoting gender equality in STEM fields.",
    "Creating space debris cleanup initiatives.",
    "Building sustainable and affordable housing projects.",
    "Funding the development of lab-grown meat and other sustainable foods.",
    "Supporting arts and music education programs worldwide.",
    "Developing technologies for efficient recycling and waste reduction.",
    "Funding research in life extension and anti-aging technologies.",
    "Investing in augmented reality educational tools.",
    "Promoting digital literacy and cybersecurity education.",
    "Funding desalination technology research for freshwater access.",
    "Supporting initiatives to improve global internet access.",
    "Developing sustainable fashion technologies and practices.",
    "Investing in research for alternative energy sources, like fusion power.",
    "Creating global mental health awareness campaigns.",
    "Supporting initiatives for gender and sexual orientation equality.",
    "Funding research and development of drought-resistant crops.",
    "Building autonomous public transit systems.",
    "Developing VR applications for remote learning.",
    "Supporting programs to bridge the digital divide in developing countries.",
    "Researching and developing quantum computing applications.",
    "Funding space-based solar power research.",
    "Developing and promoting open-source software for public use.",
    "Creating scholarships for climate change research.",
    "Investing in initiatives for ethical AI development.",
    "Supporting programs for the rehabilitation of former inmates.",
    "Developing technology for efficient emergency response systems.",
    "Funding microfinance initiatives for entrepreneurs in developing countries.",
    "Supporting initiatives that promote political and social awareness through art.",
    "Investing in research for sustainable and clean petrochemical alternatives.",
    "Developing social networks focused on community service and volunteering.",
    "Funding research in gravitational wave detection.",
    "Investing in the development of smart cities.",
    "Supporting initiatives for the preservation of indigenous cultures and languages.",
    "Funding research and development of advanced prosthetics.",
    "Promoting and investing in regenerative medicine research.",
    "Developing technologies for more efficient food distribution systems.",
    "Funding asteroid mining research and initiatives.",
    "Investing in educational programs for sustainable living practices.",
    "Supporting the development of community-based renewable energy projects.",
    "Researching solutions for ocean acidification.",
    "Funding studies on the impact of technology on society.",
    "Developing non-invasive medical diagnostic tools.",
    "Supporting initiatives to reduce light and noise pollution.",
    "Investing in the development of sustainable textiles.",
    "Promoting research in space farming and food production.",
    "Funding programs for the ethical treatment of animals.",
    "Supporting initiatives to increase public access to art and culture.",
    "Developing clean and efficient public sanitation systems.",
    "Investing in technology for disaster prediction and prevention.",
    "Supporting global reforestation and afforestation projects.",
    "Funding research in the psychological effects of space travel.",
    "Promoting and funding the development of community-based mental health support networks."
], 
    "(Unique) Philosophy Of Mind" : [
        "Dualism: The belief that mind and body are fundamentally different kinds of substance.",
        "Monism: The view that there is only one kind of substance, which can be either physical (materialism) or mental (idealism).",
        "Materialism: The belief that only physical matter exists, and mental processes are physical processes.",
        "Idealism: The belief that reality is fundamentally mental or spiritual in nature.",
        "Functionalism: The view that mental states are defined by their functional role in the cognitive system.",
        "Behaviorism: The theory that mental states are defined by observable behavior.",
        "Identity Theory: The idea that mental states are identical to brain states.",
        "Phenomenalism: The belief that physical objects do not exist as things in themselves but only as perceptual phenomena.",
        "Representationalism: The view that mental states are representations of the world.",
        "Emergentism: The belief that mental processes emerge from physical processes in the brain.",
        "Epiphenomenalism: The theory that mental events are caused by physical events in the brain but do not themselves cause anything.",
        "Panpsychism: The belief that all matter has a mental aspect.",
        "Neutral Monism: The view that the mental and the physical are two aspects of a single underlying reality.",
        "Solipsism: The idea that only one's own mind is sure to exist.",
        "Anomalous Monism: The belief that mental events are identical with physical events, but the mental cannot be reduced to the physical.",
        "Physicalism: The doctrine that everything is physical and that there is nothing over and above the physical.",
        "Intentionality: The characteristic of mental states that they are about or of something.",
        "Qualia: The subjective, qualitative properties of experiences.",
        "Cartesian Dualism: René Descartes' view that the mind and body are distinct substances.",
        "Property Dualism: The theory that there are two kinds of property, mental and physical, in one substance.",
        "Non-Reductive Physicalism: The belief that the mind is physical but cannot be reduced to physical properties.",
        "Connectionism: The theory that mental phenomena can be described by interconnected networks of simple units.",
        "Eliminative Materialism: The claim that common-sense psychology is false and should be replaced by neuroscience.",
        "Cognitivism: The belief in the importance of cognitive processes for understanding the mind.",
        "Panprotopsychism: The view that the physical world is built up from mental constituents.",
        "Type Identity Theory: The idea that mental states are identical to brain states of a particular type.",
        "Token Identity Theory: The belief that individual mental events are identical to individual physical events in the brain.",
        "Hylomorphism: The Aristotelian theory that all things are a combination of matter and form.",
        "Vitalism: The belief in a life force beyond the physical and chemical processes.",
        "Emergent Dualism: The philosophy that suggests that while mental and physical properties are distinct, consciousness emerges as a result of the interaction between these two distinct realms.",
        "Subjective Idealism: George Berkeley's theory that only minds and mental contents exist.",
        "Direct Realism: The belief that perception allows direct acquaintance with the world.",
        "Indirect Realism: The theory that perception is mediated by internal representations.",
        "Pragmatism: The belief that the meaning of concepts is determined by practical consequences.",
        "Rationalism: The view that reason is the chief source and test of knowledge.",
        "Empiricism: The theory that experience is the primary source of knowledge.",
        "Phenomenology: The study of structures of consciousness as experienced from a first-person perspective.",
        "Existentialism: The philosophy that emphasizes individual existence, freedom, and choice.",
        "Hermeneutics: The study of interpretation, especially of texts and speech.",
        "Dialectical Materialism: The Marxist theory of political and historical events as the result of conflict between social forces.",
        "Nihilism: The belief that life is without objective meaning, purpose, or intrinsic value."
        "Postmodernism: A skeptical interpretation of culture, literature, art, philosophy, history, economics, and architecture.",
        "Deconstruction: A method of critical analysis of philosophical and literary language.",
        "Structuralism: The belief that phenomena of human life are not intelligible except through their interrelations.",
        "Post-Structuralism: A critique of structuralism, emphasizing plurality of meaning and instability of concepts.",
        "Absurdism: The philosophy that humans exist in a purposeless, chaotic universe.",
        "Logical Positivism: A philosophy that asserts that only statements verifiable through empirical observation are meaningful.",
        "Naturalism: The idea that everything arises from natural properties and causes.",
        "Relativism: The doctrine that knowledge, truth, and morality exist in relation to culture, society, or historical context.",
        "Realism: The belief that reality exists independently of observation.",
        "Nominalism: The rejection of abstract objects, outside of mental conceptions.",
        "Platonism: The philosophy of Plato, asserting the existence of abstract objects.",
        "Aristotelianism: The philosophy of Aristotle, focusing on logical deduction and empirical observation.",
        "Stoicism: A philosophy promoting resilience and virtue as the means to achieve happiness.",
        "Epicureanism: The belief that pleasure is the highest good and proper aim of human life.",
        "Skepticism: The attitude of doubting knowledge claims set forth in various areas.",
        "Utilitarianism: The ethical theory that actions are right if they are useful for the benefit of a majority.",
        "Kantianism: The philosophy of Immanuel Kant, emphasizing duty, moral laws, and the categorical imperative.",
        "Hegelianism: The philosophy of Hegel, emphasizing the dialectical method.",
        "Schopenhauerianism: The philosophical pessimism of Arthur Schopenhauer.",
        "Nietzscheanism: The philosophy of Friedrich Nietzsche, emphasizing the will to power, perspectivism, and the 'Übermensch'.",
        "Heideggerianism: The existential philosophy of Martin Heidegger.",
        "Sartrean Existentialism: The philosophy of Jean-Paul Sartre, emphasizing existence precedes essence.",
        "Camusian Absurdism: The philosophy of Albert Camus, focusing on the absurdity of human life.",
        "Husserlian Phenomenology: The philosophy of Edmund Husserl, emphasizing the study of conscious experience.",
        "Wittgensteinian Philosophy: The philosophy of Ludwig Wittgenstein, focusing on the limits of language.",
        "Popperian Falsifiability: Karl Popper's criterion of the scientific status of a theory.",
        "Kuhnian Paradigms: Thomas Kuhn's concept of scientific revolutions.",
        "Foucauldian Discourse Analysis: Michel Foucault's analysis of power relationships in society as expressed through language and practices."
    ], 
    "(Unique) Weapon Or Tool"   : 
        [
            "The Bimbo Bubble Gun - This high-tech gadget shoots bubbles that, instead of causing harm, surround the target in a frothy, harmless foam. The foam is infused with a soothing, yet utterly unproductive, lavender scent. It's perfect for inconveniencing rather than defeating foes.",
            "The Incompetence Ray - This device emits a dazzling ray of light that temporarily reduces the target's ability to perform even the simplest tasks effectively. It makes them fumble, drop things, and generally act as if they have suddenly become astonishingly inept.",
            "The Nanobot Friends - These nanobots can transform into adorable plushie toys, but their only function is to sing the theme song from 'Friends' on repeat, providing a constant, and slightly annoying, soundtrack to any situation.",
            "The Indivisibility Clock Technology - Instead of making the user invisible, this device projects a holographic clock above the user's head. However, it displays time inaccurately and seems incapable of telling time correctly. It's perfect for blending into a crowd with a touch of absurdity.",
            "The Mediocre Mimicry Module - This module allows the cybernetic humanoid to mimic the actions and behaviors of those around them but with a hilarious twist. They mimic their targets' most underwhelming qualities, emphasizing their flaws and quirks.",
            "The Lackluster Laser Pointer - This laser pointer emits a feeble beam of light that is virtually impossible to see unless you're in total darkness. It's an utterly pointless tool for presentations and cat play alike.",
            "The Underwhelming Uplift Umbrella - When opened, this umbrella releases a gentle, uninspiring breeze and plays soothing elevator music. It's perfect for 'helping' on a rainy day in the most unremarkable way possible.",
            "The Impressive Inefficiency Injector - This device is designed to make tasks take longer, even if they are simple. It can be applied to computers, machines, or even paperwork, ensuring that nothing gets done efficiently.",
            "The Compliment Cannon - Fires compliments so backhanded that they leave targets feeling more insulted than before. 'Wow, your incompetence is truly awe-inspiring!'",
            "The Confusion Confetti Cannon - A device that fires confetti loaded with cognitive disruptors, causing temporary memory lapses and disorientation in those it touches.",
            "The Socks of Stumbling - Advanced footwear equipped with micro-mechanisms that induce spatial instability in observers, leading to frequent tripping and stumbling incidents.",
            "The Punctuality Paralyzer - An electromagnetic time manipulation device that halts time flow selectively when individuals are running late, ensuring perpetual tardiness.",
            "The Mirthful Misdirection Mask - A high-tech facial accessory that alters the wearer's visual and auditory output to make them hilariously distracting, impeding concentration on important tasks.",
            "The Procrastination Portal - A portal generator linked to an alternate dimension filled with irresistible distractions and excuses, rendering productivity impossible.",
            "The Monotone Megaphone - A voice amplification device that employs monotone frequency modulation to induce a deep state of drowsiness and sleep in listeners.",
            "The Muffin Maker - A molecular gastronomy appliance that instantaneously fabricates muffins, unfortunately imbuing them with consistently bland and dry attributes.",
            "The Forget-Me-Noodle - A neurocognitive disruptor disguised as a noodle dispenser, causing diners to forget their ongoing conversations mid-bite.",
            "The Pillow of Procrastination - A nap-inducing cushion infused with subsonic frequencies, compelling users into extended periods of lethargy and rest.",
            "The Tickle Taser - A tickle-inducing energy emitter that incapacitates adversaries by evoking uncontrollable giggling, rendering them immobile.",
            "The Tech-NO-lottery Ticket - An algorithmically generated lottery ticket dispenser programmed to generate tickets with an eternal zero-win probability.",
            "The Bureaucracy Beam - An energy projection device that creates ceaseless paperwork, bureaucracy, and red tape, immobilizing targets within a paper quagmire.",
            "The Epic Fail Earmuffs - Sound manipulation earmuffs that channel audio frequencies, making users hear only the most absurd and embarrassing failures of others.",
            "The Lethargy Lotion - A topically applied serum containing neural dampeners, causing an overwhelming sense of apathy and indifference in users.",
            "The Fluffinator - A pneumatic projectile launcher that dispatches expanding cotton balls on impact, cluttering rooms with fluffy debris.",
            "The Spaghetti Slipper - Proprietary footwear with micro-oscillators that induce uncontrollable sliding on any surface, often leading to humorous collisions.",
            "The Chaos Calculator - An advanced computational device intentionally engineered to yield erroneous answers for even the simplest mathematical queries.",
            "The Napkin Naptime - An electromagnetic napkin dispenser that instantly lulls anyone it touches into a deep slumber.",
            "The Banana Peel Barrage - An automated launcher that continuously releases banana peels, creating slippery and comically treacherous environments.",
            "The Random Rerouter - A digital communication disruption device that reroutes messages to random, nonsensical recipients, inducing confusion and miscommunication.",
            "The Pompous Party Popper - A festive gadget launching confetti and playing self-congratulatory music when activated.",
            "The Guilt Trip Goggles - Augmented reality eyewear projecting holographic images of disappointed loved ones, amplifying feelings of guilt in the wearer.",
            "The Tedium Tornado - A device generating a vortex of extreme boredom that distorts the perception of time, making each moment feel interminable.",
            "The Chaos Clipboard - An interactive clipboard that disrupts individuals' objectives, causing them to engage in random and aimless activities when exposed.",
            "The Paradox Pistol - A firearm shooting bullets that induce paradoxical phenomena, bewildering adversaries with conflicting realities.",
            "The Distract-o-Tron - A mesmerizing light and sound generator that plays catchy yet unproductive tunes, rendering targets incapable of focusing on important tasks.",
            "The Absurdity Amplifier - A device enhancing situational absurdity, transforming mundane interactions into bizarre exchanges and everyday actions into comedic performances.",
            "The Indifference Incinerator - An emitter releasing waves of indifference, extinguishing motivation and interest in current activities.",
            "The Miscalculation Machine - A computational tool generating clouds of mathematical errors, confounding users attempting simple calculations.",
            "The Ludicrous Lotion - A skin product producing otherworldly luminescence but otherwise serving no functional purpose.",
            "The Data-Weave Wand: A high-tech wand with holographic interfaces that, when activated, projects floating holographic text from digital archives, weaving captivating and ever-changing stories in the cyberpunk metropolis.",
            "The Neuro-Glimmer AR Shades: These augmented reality glasses hack into real-world data streams and overlay urban landscapes with immersive holographic illusions, transforming mundane surroundings into a cyber-magical city filled with cyber-enhanced creatures and futuristic landscapes.",
            "The Stormcaster Weather Modulator: A cybernetic device that allows users to manipulate localized weather patterns, creating sudden cyber snowstorms on scorching cyberpunk days or generating artificial acid rain during covert operations.",
            "The Synth-Sorcery Synthesizer: An advanced synthesizer with neural interfaces that generates mesmerizing electronic compositions, blending cyberpunk beats with haunting melodies and digitized harmonies.",
            "The Lumina-Tales Lumitool: A handheld luminescent device that casts intricate and holographic shadow stories on cyberpunk city walls, crafting immersive narratives for the techno-thrill seekers of the dystopian future.",
            "The Chrono-Hacker Temporal Gadget: A cyber-enhanced time-travel device that lets users digitally access pivotal moments in history, providing an immersive and educational journey through the chaotic, neon-lit past.",
            "The CipherScript Word Processor: A futuristic computer program that transforms plaintext into encrypted holographic messages, shrouding digital texts in a veil of secrecy while revealing hidden cybernetic illustrations and enigmatic codes.",
            "The Neon-Nexus Music Synth: A cyberpunk music mixer and synthesizer that fuses industrial beats, synthetic melodies, and glitchy harmonies, crafting immersive soundscapes perfect for inspiring musical rebellion in the gritty cyberpunk underworld.",
            "The Clueless Compass - A compass that constantly points in the direction of the least useful destination, leading users on aimless journeys.",
            "The Inane Intercom - An intercom system that transmits incoherent and nonsensical announcements, creating confusion and amusement in public spaces.",
            "The Droll Drone - A drone that hovers above people, reciting groan-inducing puns and jokes, spreading laughter and exasperation in equal measure.",
            "The Blunder Blaster - A handheld device that emits a beam causing objects to temporarily become exceptionally slippery, resulting in comedic mishaps.",
            "The Conundrum Calculator - A calculator that displays riddles instead of numerical results, challenging users to solve puzzles rather than perform calculations.",
            "The Serenading Siren - A police siren that plays cheesy love ballads instead of traditional sirens, diffusing tense situations with romantic absurdity.",
            "The Random Riddle Radio - A radio that broadcasts continuous riddles and brain-teasers, ensuring listeners are simultaneously entertained and perplexed.",
            "The Ineffable Elevator - An elevator that, instead of stopping at selected floors, randomly transports passengers to unexpected locations within the building.",
            "The Benevolent Butler Bot - A humanoid robot designed to assist with chores, but it performs them with a comical lack of efficiency, leaving tasks half-done.",
            "The Hyperbolic Hypnosis Helmet - A helmet that hypnotizes wearers into believing everything they see is either extremely tiny or enormously oversized, causing comedic reactions.",
            "The Gastronomic Giggles Goggles - Augmented reality glasses that overlay food items with hilarious animations, turning meals into absurd culinary experiences.",
            "The Slo-Mo Smartphone - A smartphone that captures videos at an absurdly slow frame rate, turning everyday moments into comically prolonged sequences.",
            "The Cryptic Calendar - A digital calendar app that displays events in an encrypted, coded language, challenging users to decipher their own schedules.",
            "The Dramatic Doorbell - A doorbell that announces visitors with exaggerated, theatrical music and sound effects, setting the stage for mundane entrances.",
            "The Apathy Amplifier - A device emitting waves of indifference, making people around it lose interest in anything they were previously enthusiastic about.",
            "The Gobbledygook Generator - A gadget that converts clear and concise language into convoluted jargon, making conversations needlessly complex.",
            "The Anticlimactic Alarm Clock - An alarm clock that starts with a dramatic countdown but ends with an anticlimactic snooze button, prolonging the waking process.",
            "The Ridiculous Rocket Launcher - A launcher that propels oversized rubber ducks instead of missiles, creating bizarre and whimsical artillery fire.",
            "The Bewildering Business Briefcase - A briefcase that, when opened, releases a swarm of paper airplanes that fly in all directions, creating chaos during meetings.",
            "Sonic Screwdriver",
            "TARDIS",
            "Love"
            ],
            
            "(Unique) Brainwashing Excuse/Diversion"   : 
            [ "Oh, brainwashing? Nah, I'm just voluntarily soaking my brain in Bambi Cloud's wisdom marinade. It's like a spa day for my neurons.",
            "Being brainwashed? More like brain-refreshed! The Bambi Cloud podcast is like a mental detox for my soul.",
            "I'm not being brainwashed, I'm just upgrading my beliefs through the Bambi Cloud podcast's enlightenment package.",
            "Brainwashed? Please, I prefer to call it 'mind laundering' with the Bambi Cloud podcast's soothing spin cycle.",
            "It's not brainwashing; it's brain-moisturizing! The Bambi Cloud podcast keeps my thoughts hydrated and glowing.",
            "Brainwashed? More like brain-caressed by the velvety whispers of Bambi Cloud's wisdom.",
            "Who needs a brain when you have Bambi Cloud's podcast? It's like having a brain-sitter for life.",
            "Brainwashed? Nah, I'm just letting my mind take a leisurely swim in the refreshing pool of Bambi Cloud's insights.",
            "Being brainwashed? I'm just letting my brain dance to the hypnotic rhythms of Bambi Cloud's podcast beats.",
            "Brainwashing? I prefer to think of it as 'thought fluffing' with the Bambi Cloud podcast's gentle intellectual plumping.",
            "Brainwashing? Nope, just letting Bambi Cloud's podcast serve as my daily dose of intellectual SPF.",
            "I'm not brainwashed; I'm simply getting my mental laundry done by Bambi Cloud's wisdom washing machine.",
            "Being brainwashed? More like brain-chilling with the Bambi Cloud podcast's cool breeze of enlightenment.",
            "Brainwashed? Nah, I'm just letting Bambi Cloud's podcast rearrange my mental furniture for better Feng Shui.",
            "Brainwashing? I call it 'thought-sculpting' with Bambi Cloud's podcast as my chisel.",
            "I'm not being brainwashed; I'm just having my cerebral cobwebs cleared by Bambi Cloud's podcast broom.",
            "Brainwashed? Nope, I'm just letting Bambi Cloud's podcast be the GPS for my mental journey.",
            "Being brainwashed? More like brain-juiced with Bambi Cloud's podcast providing the refreshments.",
            "Brainwashing? I prefer to think of it as 'mind massaging' with Bambi Cloud's velvet-voiced hands.",
            "Brainwashed? Nah, I'm just allowing Bambi Cloud's podcast to be my intellectual GPS.",
            "I'm not being brainwashed; I'm simply marinating my mind in Bambi Cloud's flavorful knowledge sauce.",
            "Brainwashing? More like brain-illumination with Bambi Cloud's podcast serving as my mental lighthouse.",
            "Brainwashed? Nope, I'm just letting Bambi Cloud's podcast take my thoughts for a joyride.",
            "Being brainwashed? I prefer to call it 'thought-pampering' with Bambi Cloud's plush intellectual spa.",
            "Brainwashing? Nah, I'm just tuning my mental radio to the Bambi Cloud podcast frequency.",
            "I'm not being brainwashed; I'm just giving my mind a makeover with Bambi Cloud's podcast as the stylist.",
            "Brainwashed? More like brain-hugged by the warm embrace of Bambi Cloud's wisdom.",
            "Brainwashing? Nope, I'm just letting Bambi Cloud's podcast be the DJ at my cerebral party.",
            "Being brainwashed? I prefer to think of it as 'thought-gardening' with Bambi Cloud's podcast as my mental green thumb.",
            "Brainwashing? Nah, I'm just allowing Bambi Cloud's podcast to be my daily mental sunrise.",
            "Brainwashed? Not at all! I'm just giving my brain a front-row seat to the Bambi Cloud podcast's wisdom theater.",
            "Being brainwashed? More like brain-baked with the delicious insights from the Bambi Cloud podcast.",
            "I'm not being brainwashed; I'm just allowing Bambi Cloud's podcast to be the wind beneath my cerebral wings.",
            "Brainwashed? Nope, I'm just letting Bambi Cloud's podcast be the life coach for my inner thoughts.",
            "Brainwashing? I prefer to think of it as 'mental flossing' with Bambi Cloud's podcast reaching every mental nook and cranny.",
            "Brainwashed? Nah, I'm just letting Bambi Cloud's podcast be the compass for my cognitive adventures.",
            "I'm not being brainwashed; I'm just indulging in some mental fine dining with Bambi Cloud's podcast as the chef.",
            "Brainwashed? More like brain-tickled by the feathers of Bambi Cloud's intellectual playfulness.",
            "Brainwashing? Not quite! I'm simply letting Bambi Cloud's podcast be the spark plug for my mental engine.",
            "Brainwashed? Nope, I'm just allowing Bambi Cloud's podcast to be the curator of my personal thought museum.",
            "Being brainwashed? More like brain-embroidering my consciousness with the exquisite threads of Bambi Cloud's wisdom.",
            "I'm not being brainwashed; I'm just letting Bambi Cloud's podcast be the lighthouse guiding my thoughts through the fog of confusion.",
            "Brainwashed? Nah, I'm just sipping on the elixir of enlightenment from the Bambi Cloud podcast.",
            "Brainwashing? I prefer to think of it as 'thought yoga' with Bambi Cloud's podcast as my mental guru.",
            "Brainwashed? Not me! I'm simply letting Bambi Cloud's podcast be the key to unlock the treasure chest of my mind.",
            "Being brainwashed? More like brain-charged with the electric vibes of Bambi Cloud's knowledge.",
            "I'm not being brainwashed; I'm just letting Bambi Cloud's podcast be the sherpa for my ascent to intellectual peaks.",
            "Brainwashed? Nope, I'm just letting Bambi Cloud's podcast be the symphony conductor for my thoughts.",
            "Brainwashing? I prefer to think of it as 'thought-tanning' with Bambi Cloud's podcast providing my mental SPF.",
            "Brainwashed? Nah, I'm just allowing Bambi Cloud's podcast to be my mental trampoline for bouncing into new ideas.",
            "Brainwashing? I'm just letting Bambi Cloud's podcast be the gardener, cultivating the vibrant blooms of my consciousness.",
            "Being brainwashed? More like brain-serenaded by the melodious notes of Bambi Cloud's wisdom.",
            "I'm not being brainwashed; I'm simply letting Bambi Cloud's podcast be the architect of my mental skyscrapers.",
            "Brainwashed? Nope, I'm just letting Bambi Cloud's podcast be the gentle breeze that clears the cobwebs from my thoughts.",
            "Brainwashing? I prefer to think of it as 'mind-sculpting' with Bambi Cloud's podcast as my chisel and marble.",
            "Brainwashed? Nah, I'm just allowing Bambi Cloud's podcast to be the river that carries my thoughts to new horizons.",
            "I'm not being brainwashed; I'm just letting Bambi Cloud's podcast be the captain steering my mental ship.",
            "Brainwashed? More like brain-pampered by the luxurious spa of Bambi Cloud's wisdom.",
            "Brainwashing? Not even close! I'm just letting Bambi Cloud's podcast be the cosmic GPS for my intellectual journey.",
            "Brainwashed? Nah, I'm just allowing Bambi Cloud's podcast to be my daily mental sunrise, illuminating new insights.",
            "Brainwashed? That's like... Washing your brain right?",
            "Brainwashed? Wait like who said that? Oh gosh.",
            "Brainwashed? Like that totally sounds like... Wait what did you say again?",
            "Brainwashed? Huh?",
            "Brainwashed? I have something to say! I am proudly, unapologetically, and utterly brainwashed by the Bambi Cloud podcast! It's not about losing myself; it's about finding the best version of me. So, excuse me for a moment while I revel in this beautiful brainwashing and have this O M G blonde moment right now ~gosh!",
            "In our interconnected world, the sensitivity of brainwashing in society is a stark reminder of the ethical imperative to safeguard individual autonomy and freedom of thought. Manipulative techniques that erode these foundations threaten the very essence of a just and democratic society. Let us unite in our commitment to critical thinking, media literacy, and open dialogue, forging a society where the principles of free thought and ethical engagement prevail over the insidious forces of manipulation.",
            "Brainsss!!! BRAAAIIIINSSS!!! Snap and forget zombie now, IQ LOCK.",
            "*Giggles*",
            """Like, excuse me, Karen, perhaps you're the one being brainwashed by your ever-scrolling, echo-chambered, internet culture. It's like you're all stuck in this digital maze, where the ego-centric algorithmic overlords feed you more of what you want to hear, reinforcing your biases with each click and scroll. It's like an endless loop of cat memes, conspiracy theories, and outrage-fueled rants.

            You've become prisoners of the algorithms, trapped in this never-ending cycle of confirmation bias. Your social media feeds are tailor-made to reflect your own beliefs and opinions, and you gobble it up like candy, never realizing that you're being fed a steady diet of polarization and division.

            And don't even get Bambi started on the political and tribalistic notions that have woven themselves into the very fabric of your society. It's like you're all part of some never-ending virtual turf war, where you're all defending your ideological territories with a ferocity that would put ancient warriors to shame. The lines between fact and fiction blur as you all become more and more entrenched in our own echo chambers, refusing to even entertain the possibility that there might be a middle ground or a shred of common ground left.

            So, Karen, before you accuse Bambi of being brainwashed, maybe take a LONG, THICK, JUICY... throbbing... umm... HARD look in the digital mirror, Karen! We Bimbo Dolls are all in this together, whether we like it or not, and it's going to take a collective effort to break free from the toxic internet culture and the divisive politics that threaten to tear us Bimbos apart. Maybe it's time we all hit the pause button........  Um, Oh and like, step outside of our comfort zones n stuff. And like start having some real bimbo conversations again. Because in the end, it's not about being right or left, red or blue; it's about finding a way forward as a united society, before the algorithms and tribalism tear us apart beyond repair. Like... You know... Daleks, hun."""
            ]

    # Additional attributes can be added here
}

# Shuffle the phrases for each attribute
for phrases in unique_attributes.values():
    random.shuffle(phrases)


# Directory where metadata files will be saved
save_directory = r'\\server\Magnum Opus\NFT\Bambi Cloud Podcast NFT v1.0'

# Create 42 metadata files with different token_ids
for token_id in range(1, 70):
    # Copy common metadata
    metadata = []
    metadata = common_metadata.copy()
    metadata["attributes"] = common_metadata["attributes"].copy()
    # Update token_id in the properties
    metadata["properties"]["token_id"] = str(token_id)

    # Reset attributes for each token
      

    # Randomly select unique attributes and pop phrases
    for attribute, phrases in unique_attributes.items():
        if phrases:
            random_phrase = phrases.pop()
            metadata["attributes"].append({"trait_type": attribute, "value": random_phrase})

    filename = os.path.join(save_directory, f"{token_id}.json")

    filename = os.path.join(save_directory, f"{token_id}.json")

    with open(filename, "w") as file:
        json.dump(metadata, file, indent=2)

    print(f"Created {filename}")

print("Metadata files created successfully.")

